// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import type { NextjsLayerOverrides } from '../';

/**
 * OptionalNextjsLayerProps
 */
export interface OptionalNextjsLayerProps {
  /**
   * Override props for every construct.
   * @stability stable
   */
  readonly overrides?: NextjsLayerOverrides;
}
